services:
  nginx:
    build: ./Docker/web/
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      - APP_URL=${APP_URL:-http://localhost}

  node:
    tty: true
    build: ./Docker/node/
    volumes:
      - ./app:/app
  php:
    tty: true
    build: ./Docker/php/
    volumes:
          - ./app:/app
    environment:
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-cms}
      - DB_USERNAME=${DB_USERNAME:-app}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    extra_hosts:
    - "host.docker.internal:host-gateway"
  database:
    image: "mysql:9.3.0"
    environment:
       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-secret123}
       - MYSQL_DATABASE=${DB_DATABASE:-cms}
       - MYSQL_USER=${DB_USERNAME:-app}
       - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2-fpm-alpine
    ports:
      - "8000:80"
    environment:
       - PMA_HOST=database

