services:
  nginx:
    build: ./Docker/web/
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      - APP_URL=$APP_URL

  php:
    tty: true
    build: ./Docker/php/
    volumes:
          - ./app:/app
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    extra_hosts:
    - "host.docker.internal:host-gateway"
  database:
    image: "mysql:9.3.0"
    environment:
       - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
       - MYSQL_DATABASE=$DB_DATABASE
       - MYSQL_USER=$DB_USERNAME
       - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2-fpm-alpine
    ports:
      - "8000:80"
    environment:
       - PMA_HOST=database

